apiVersion: v1
kind: Secret
metadata:
  name: ithust-backend-secret
  namespace: production
type: Opaque
data:
  secret-key-one: MTE1MTc5YWZiYjI1ZDdlMDYwNzA1M2MyYTVhMDBkM2Q=
  secret-key-two: ZDhjMmEzOTgwMTVjNzUzNDQzMWFmYjc5ODYxN2NlOTQ=
  gateway-jwt-token: MTZjOGE2NmRmZDBhYjA4MTA0Nzg0MGUzYzA0YzUyMGU=
  jwt-token: ZTNhZTdmYmIwMGEzNjYzOGMwYThlZTM1ZTNhMDRhN2Y=
  ithust-redis-host: cmVkaXM6Ly9pdGh1c3QtcmVkaXMtY2x1c3Rlci5mbXB0dGIubmcuMDAwMS5hcHNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  sender-email: YnJhbm5vbi5rcmFqY2lrODdAZXRoZXJlYWwuZW1haWw=
  sender-email-password: M3VXaFlacWtXczIzblRUWGRI
  ithust-mysql-db: bXlzcWw6Ly9pdGh1c3RhZG1pbjppa0FXUzIwMDRAaXRodXN0LWF1dGgtZGIuYzN5NmU4b3dxandhLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tL2l0aHVzdF9hdXRo
  ithust-postgres-host: aXRodXN0LXBvc3RncmVzLmMzeTZlOG93cWp3YS5hcC1zb3V0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  ithust-postgres-user: aXRodXN0YWRtaW4=
  ithust-postgres-password: aWtBV1MyMDA0
  cloud-name: ZGJ4YTFrMXcx
  cloud-api-key: OTczOTE3NTc0ODgxOTg3
  cloud-api-secret: SmU1LWFUalZ5SEppcXlXNDczNFZ5cWxReXhJ
  mongo-database-url: bW9uZ29kYitzcnY6Ly9pdGh1c3RhZG1pbjppa01HREIyMDA0JTQwQGl0aHVzdC4wMzZvd2UwLm1vbmdvZGIubmV0Lz9hcHBOYW1lPWl0aHVzdA==
  stripe-api-key: c2tfdGVzdF81MVJQMFNZUjRhYTFqc1Bzb1NTTWdHQjBOZHNiOWp6TGdrUFdtSXFyVkMzSVI2bFlIdUFycjFoUE1CSlZBMFRBaE5Da1ZlZm5SeFV2OXJ2U2Yxc21KSUtubzAwY0xSNEN6QjA=
  stripe-client-key: c2tfdGVzdF81MVJQMFNZUjRhYTFqc1Bzb1NTTWdHQjBOZHNiOWp6TGdrUFdtSXFyVkMzSVI2bFlIdUFycjFoUE1CSlZBMFRBaE5Da1ZlZm5SeFV2OXJ2U2Yxc21KSUtubzAwY0xSNEN6QjA=
  ithust-rabbitmq-user: aXRodXN0
  ithust-rabbitmq-password: aXRodXN0cGFzcw==
  ithust-rabbitmq-endpoint: YW1xcDovL2l0aHVzdDppdGh1c3RwYXNzQGl0aHVzdC1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  ithust-elasticsearch-url: aHR0cHM6Ly9lbGFzdGljOlRzY2hIRXY2eE1odVowUFdaczFsaTdMUkBpdGh1c3RhcHAtZWUwM2YxLmVzLmFzaWEtc291dGhlYXN0MS5nY3AuZWxhc3RpYy1jbG91ZC5jb20=
  ithust-elastic-apm-server-url: aHR0cHM6Ly80YmZiMzUwNjU4MDQ0ZDA0OWQ2NDVhYjRlNTUzMzA2MC5hcG0uYXNpYS1zb3V0aGVhc3QxLmdjcC5lbGFzdGljLWNsb3VkLmNvbTo0NDM=
  ithust-elastic-apm-secret-token: dnZzZFBrTDhKRUpkQkJjeVJB
  ithust-elasticsearch-host: aXRodXN0YXBwLWVlMDNmMS5lcy5hc2lhLXNvdXRoZWFzdDEuZ2NwLmVsYXN0aWMtY2xvdWQuY29t
  ithust-elasticsearch-username: ZWxhc3RpYw==
  ithust-elasticsearch-password: VHNjaEhFdjZ4TWh1WjBQV1pzMWxpN0xS
  ithust-elastic-cloud-id: aXRodXN0YXBwOllYTnBZUzF6YjNWMGFHVmhjM1F4TG1kamNDNWxiR0Z6ZEdsakxXTnNiM1ZrTG1OdmJUbzBORE1rWXpFek1Ua3pNbUZoTmpoak5EZzNaV0psWm1JNE5EbGxOVFk0TURSaU1qZ2tPREJrT1dFek1EUmxaak5rTkdRMk4yRXhaR1E0TjJSbU9UbGpZakV6WWpRPQ==
  # <elasticsearch-username>:<elasticsearch-password>
  ithust-elastic-cloud-auth: ZWxhc3RpYzpUc2NoSEV2NnhNaHVaMFBXWnMxbGk3TFI=