apiVersion: v1
kind: Secret
metadata:
  name: ithust-backend-secret
  namespace: production
type: Opaque
data:
  secret-key-one: MTE1MTc5YWZiYjI1ZDdlMDYwNzA1M2MyYTVhMDBkM2Q=
  secret-key-two: ZDhjMmEzOTgwMTVjNzUzNDQzMWFmYjc5ODYxN2NlOTQ=
  gateway-jwt-token: MTZjOGE2NmRmZDBhYjA4MTA0Nzg0MGUzYzA0YzUyMGU=
  jwt-token: ZTNhZTdmYmIwMGEzNjYzOGMwYThlZTM1ZTNhMDRhN2Y=
  ithust-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAaXRodXN0LXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  sender-email: YnJhbm5vbi5rcmFqY2lrODdAZXRoZXJlYWwuZW1haWw=
  sender-email-password: M3VXaFlacWtXczIzblRUWGRI
  ithust-mysql-db: bXlzcWw6Ly9pdGh1c3Q6YXBpQGl0aHVzdC1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDcvaXRodXN0X2F1dGg=
  ithust-postgres-host: aXRodXN0LXBvc3RncmVzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  ithust-postgres-user: aXRodXN0
  ithust-postgres-password: YXBp
  cloud-name: ZGJ4YTFrMXcx
  cloud-api-key: OTczOTE3NTc0ODgxOTg3
  cloud-api-secret: SmU1LWFUalZ5SEppcXlXNDczNFZ5cWxReXhJ
  mongo-database-url: bW9uZ29kYjovL2l0aHVzdC1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2l0aHVzdA==
  stripe-api-key: c2tfdGVzdF81MVJQMFNZUjRhYTFqc1Bzb1NTTWdHQjBOZHNiOWp6TGdrUFdtSXFyVkMzSVI2bFlIdUFycjFoUE1CSlZBMFRBaE5Da1ZlZm5SeFV2OXJ2U2Yxc21KSUtubzAwY0xSNEN6QjA=
  stripe-client-key: c2tfdGVzdF81MVJQMFNZUjRhYTFqc1Bzb1NTTWdHQjBOZHNiOWp6TGdrUFdtSXFyVkMzSVI2bFlIdUFycjFoUE1CSlZBMFRBaE5Da1ZlZm5SeFV2OXJ2U2Yxc21KSUtubzAwY0xSNEN6QjA=
  ithust-rabbitmq-user: aXRodXN0
  ithust-rabbitmq-password: aXRodXN0cGFzcw==
  ithust-rabbitmq-endpoint: YW1xcDovL2l0aHVzdDppdGh1c3RwYXNzQGl0aHVzdC1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  ithust-elasticsearch-url: aHR0cDovL2VsYXN0aWM6YWRtaW4xMjM0QGl0aHVzdC1lbGFzdGljLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6OTIwMA==
  ithust-elastic-apm-server-url: ""
  ithust-elastic-apm-secret-token: ""
  ithust-elasticsearch-host: aXRodXN0LWVsYXN0aWMucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbA==
  ithust-elasticsearch-username: ZWxhc3RpYw==
  ithust-elasticsearch-password: YWRtaW4xMjM0
