FROM node:22-alpine3.18

WORKDIR /app

RUN npm install -g nodemon

COPY package*.json ./
COPY .npmrc ./

RUN npm install && \
    npm cache clean --force && \
    rm -f .npmrc

COPY tsconfig.json ./
COPY src ./src

EXPOSE 4007

CMD [ "npm", "run", "dev" ]