apiVersion: apps/v1
kind: Deployment
metadata:
  name: ithust-auth
  namespace: production
spec:
  selector:
    matchLabels:
      app: ithust-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ithust-auth
    spec:
      containers:
        - name: ithust-auth
          image: minhkhoi779/ithust-auth:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 192Mi
          ports:
            - name: auth
              containerPort: 4002
          env:
            - name: ENABLE_APM
              value: "0"
            - name: NODE_ENV
              value: "production"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-rabbitmq-endpoint
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-mysql-db
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: cloud-api-secret
            - name: CLIENT_URL
              value: "https://ithust.shop"
            - name: API_GATEWAY_URL
              value: "http://ithust-gateway.production.svc.cluster.local:4000"
            - name: PLATFORM_OWNER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: platform-owner-email
            - name: PLATFORM_OWNER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: platform-owner-username
            - name: PLATFORM_OWNER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: platform-owner-password
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-elastic-apm-secret-token
