apiVersion: apps/v1
kind: Deployment
metadata:
  name: ithust-kibana
  namespace: production
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ithust-kibana
  template:
    metadata:
      labels:
        app: ithust-kibana
    spec:
      containers:
        - name: ithust-kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
          - name: ithust-kibana
            containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port-number>
              value: http://ithust-elastic.production.svc.cluster.local:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              # add to secret file
              value: kibana
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              value: AAEAAWVsYXN0aWMva2liYW5hL2l0aHVzdC1raWJhbmE6U1FJZTVxVGpRcTJUWjc2T05Lak1Ddw
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config