apiVersion: apps/v1
kind: Deployment
metadata:
  name: ithust-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ithust-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ithust-gateway
    spec:
      containers:
        - name: ithust-gateway
          image: minhkhoi779/ithust-gateway:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 120Mi
          ports:
            - name: gateway
              containerPort: 4000
          env:
            - name: ENABLE_APM
              value: "0"
            - name: NODE_ENV
              value: "production"
            - name: SECRET_KEY_ONE
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: secret-key-one
            - name: SECRET_KEY_TWO
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: secret-key-two
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: jwt-token
            - name: CLIENT_URL
              value: "https://ithust.shop"
            - name: CLIENT_URLS
              value: "https://ithust.shop,https://ithust.store"
            - name: AUTH_BASE_URL
              value: "http://ithust-auth.production.svc.cluster.local:4002"
            - name: USERS_BASE_URL
              value: "http://ithust-users.production.svc.cluster.local:4003"
            - name: GIG_BASE_URL
              value: "http://ithust-gig.production.svc.cluster.local:4004"
            - name: MESSAGE_BASE_URL
              value: "http://ithust-chat.production.svc.cluster.local:4005"
            - name: ORDER_BASE_URL
              value: "http://ithust-order.production.svc.cluster.local:4006"
            - name: REVIEW_BASE_URL
              value: "http://ithust-review.production.svc.cluster.local:4007"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-redis-host
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-elastic-apm-secret-token
