apiVersion: apps/v1
kind: Deployment
metadata:
  name: ithust-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ithust-queue
  template:
    metadata:
      labels:
        app: ithust-queue
    spec:
      containers:
        - name: ithust-queue
          image: rabbitmq:3.12.8-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: ithust-backend-secret
                  key: ithust-rabbitmq-password
          resources:
            limits:
              memory: "800Mi"
              cpu: "0.5"
            requests:
              memory: 120Mi
              cpu: 100m
          ports:
            - name: queue
              containerPort: 5672
              protocol: TCP
            - name: mgmt
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbittmq-local-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbittmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
