name: Deploy ITHust Gig

on:
  push:
    branches: ['dev/se-pay']
    paths:
      - 'server/5-gig-service/**'
      - 'kubernetes/k3s/5-gig-service/**'
      - '.github/workflows/deploy-gig.yml'
      - '.github/workflows/_deploy-backend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-gig
      service_label: "ITHust Gig"
      image_name: minhkhoi779/ithust-gig
      service_dir: server/5-gig-service
      k8s_dir: kubernetes/k3s/5-gig-service
    secrets: inherit
