name: Deploy ITHust Gateway

on:
  push:
    branches: ['production']
    paths:
      - 'server/1-gateway-service/**'
      - 'kubernetes/k3s/1-gateway-service/**'
      - '.github/workflows/deploy-gateway.yml'
      - '.github/workflows/_deploy-backend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-gateway
      service_label: "ITHust Gateway"
      image_name: minhkhoi779/ithust-gateway
      service_dir: server/1-gateway-service
      k8s_dir: kubernetes/k3s/1-gateway-service
    secrets: inherit
