name: Deploy ITHust Chat

on:
  push:
    branches: ['production']
    paths:
      - 'server/6-chat-service/**'
      - 'kubernetes/k3s/6-chat-service/**'
      - '.github/workflows/deploy-chat.yml'
      - '.github/workflows/_deploy-backend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-chat
      service_label: "ITHust Chat"
      image_name: minhkhoi779/ithust-chat
      service_dir: server/6-chat-service
      k8s_dir: kubernetes/k3s/6-chat-service
    secrets: inherit
