name: Deploy ITHust Reviews

on:
  push:
    branches: ['production']
    paths:
      - 'server/8-review-service/**'
      - 'kubernetes/k3s/8-review-service/**'
      - '.github/workflows/deploy-review.yml'
      - '.github/workflows/_deploy-backend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-review
      service_label: "ITHust Reviews"
      image_name: minhkhoi779/ithust-review
      service_dir: server/8-review-service
      k8s_dir: kubernetes/k3s/8-review-service
    secrets: inherit
