name: Deploy ITHust Auth

on:
  push:
    branches: ['dev/se-pay']
    paths:
      - 'server/3-auth-service/**'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-auth
      service_label: "ITHust Auth"
      image_name: minhkhoi779/ithust-auth
      service_dir: server/3-auth-service
      k8s_dir: kubernetes/k3s/3-auth-service
    secrets: inherit
