name: Deploy ITHust Notification

on:
  push:
    branches: ['dev/se-pay']
    paths:
      - 'server/2-notification-service/**'
      - 'kubernetes/k3s/2-notifications-service/**'
      - '.github/workflows/deploy-notification.yml'
      - '.github/workflows/_deploy-backend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-notification
      service_label: "ITHust Notification"
      image_name: minhkhoi779/ithust-notification
      service_dir: server/2-notification-service
      k8s_dir: kubernetes/k3s/2-notifications-service
    secrets: inherit
