name: Deploy ITHust Order

on:
  push:
    branches: ['dev/se-pay']
    paths:
      - 'server/7-order-service/**'
      - 'kubernetes/k3s/7-order-service/**'
      - '.github/workflows/deploy-order.yml'
      - '.github/workflows/_deploy-backend.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      service_name: ithust-order
      service_label: "ITHust Order"
      image_name: minhkhoi779/ithust-order
      service_dir: server/7-order-service
      k8s_dir: kubernetes/k3s/7-order-service
    secrets: inherit
